## File generated by the BNF Converter (bnfc 2.9.3).
FILES=Main.hs Interpreter.hs

# Makefile for building the parser, test program and FlatWhite interpreter.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestFlatwhite interpreter

# Rules for building the parser.

AbsFlatwhite.hs LexFlatwhite.x ParFlatwhite.y PrintFlatwhite.hs TestFlatwhite.hs : flatwhite.cf
	bnfc --haskell --functor flatwhite.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestFlatwhite : AbsFlatwhite.hs LexFlatwhite.hs ParFlatwhite.hs PrintFlatwhite.hs TestFlatwhite.hs
	${GHC} ${GHC_OPTS} $@

interpreter: *.hs
	ghc --make ${FILES} -o interpreter

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi interpreter

distclean : clean
	-rm -f AbsFlatwhite.hs AbsFlatwhite.hs.bak ComposOp.hs ComposOp.hs.bak DocFlatwhite.txt DocFlatwhite.txt.bak ErrM.hs ErrM.hs.bak LayoutFlatwhite.hs LayoutFlatwhite.hs.bak LexFlatwhite.x LexFlatwhite.x.bak ParFlatwhite.y ParFlatwhite.y.bak PrintFlatwhite.hs PrintFlatwhite.hs.bak SkelFlatwhite.hs SkelFlatwhite.hs.bak TestFlatwhite.hs TestFlatwhite.hs.bak XMLFlatwhite.hs XMLFlatwhite.hs.bak ASTFlatwhite.agda ASTFlatwhite.agda.bak ParserFlatwhite.agda ParserFlatwhite.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak flatwhite.dtd flatwhite.dtd.bak TestFlatwhite LexFlatwhite.hs ParFlatwhite.hs ParFlatwhite.info ParDataFlatwhite.hs Makefile


# EOF
